global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'calculator_app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:8080']
